apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnops-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/maplechori/c2'
    targetRevision: feature/create-kubernetes
    path: 'argocd/apps/config'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  