apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: endpoint
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/maplechori/c2
    targetRevision: feature/create-kubernetes
    path: argocd/apps/endpoint
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  